{% set name = "condansis" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fe23008f0184eeda2812987458520cb00f682738a23c4a9ebe25c387fb7e54b1

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - jinja2
    - nsis
    - conda-pack >=0.5.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - condansis

about:
  home: https://github.com/guilhermebs/condansis
  summary: Build self-extracting Windows installers for your python app
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt


extra:
  recipe-maintainers:
    - guilhermebs
